### ISSUE TITLE
Are SMT semantics stored somewhere?

### ISSUE THREAD

**Issue by ntc2** [StanfordPL/strata-data#1]
I was curious to see the SMT representation of the semantics, but I can't find it in this repo for base or learned instructions.

E.g. https://github.com/StanfordPL/strata-data/blob/master/data-regs/instructions/andl_r32_r32/andl_r32_r32.meta.json specifies the input and output locations of `andl r32 r32` and https://github.com/StanfordPL/strata-data/blob/master/data-regs/instructions/andl_r32_r32/results/result-00000.s gives a learned implementation of `andl r32 r32` in terms of lower strata instructions. Are the SMT formulas that correspond to the learned implementation stored anywhere?

I could imagine that only the base instructions have the semantics actually written down somewhere, but I couldn't find that either. All I could find was the list of base instructions: https://github.com/StanfordPL/strata-data/blob/master/data-regs/information/initial_base.instrs.

Thanks for making these artifacts from your paper available online!

**Comment by stefanheule** [comment]
Yes, you can indeed inspect the learned semantics, but there are not directly stored in a file.  Instead, we provide code to compute them (from the base instructions, as well as the learned programs).  You can find instructions for this process here: https://stefanheule.com/s/projects/strata/

If you want to see the base instruction semantics, you can either look at the source code (they are simple C++ functions that assemble the SMT formulas for a given instruction; see `stoke/src/validator/handlers`).

I'll close this issue, hoping this answers your question.  If not, or if something doesn't work as expected, please do let me know.
